all:
  hosts:
    node1:
      ansible_host: 192.168.1.167
      ip: 192.168.1.167
      access_ip: 192.168.1.167
    node2:
      ansible_host: 192.168.255.89
      ip: 192.168.255.89
      access_ip: 192.168.255.89
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
