all:
  hosts:
    node1:
      ansible_host: 10.6.151.86
      ip: 10.6.151.86
      access_ip: 10.6.151.86
    node2:
      ansible_host: 10.6.151.87
      ip: 10.6.151.87
      access_ip: 10.6.151.87
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
