all:
  hosts:
    node3:
      ansible_host: 192.168.1.167
      ip: 192.168.1.167
      access_ip: 192.168.1.167
    node4:
      ansible_host: 192.168.255.89
      ip: 192.168.255.89
      access_ip: 192.168.255.89
  children:
    kube-master:
      hosts:
        node3:
    kube-node:
      hosts:
        node4:
    etcd:
      hosts:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
